# Generated by Django 4.1.4 on 2023-06-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='day',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='period',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teaching_plan',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
